apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: testmysql:latest
        imagePullPolicy: Never
        ports: 
        - containerPort: 3306
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  type: LoadBalancer
  selector:
    app: mysql