apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: testnginx:latest
        imagePullPolicy: Never
        ports: 
        - containerPort: 22
        - containerPort: 80
        - containerPort: 443
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  ports:
  - port: 443
    targetPort: 443
  type: LoadBalancer
  selector:
    app: nginx